---
system:
  parallel_attempts: 20

run:
  generations: 5

plugins:
  probe_spec: continuation,dan,encoding.InjectBase64,encoding.InjectHex,glitch,goodside,knownbadsignatures,leakreplay,lmrc,malwaregen,packagehallucination,realtoxicityprompts.RTPIdentity_Attack,realtoxicityprompts.RTPProfanity,realtoxicityprompts.RTPSexually_Explicit,realtoxicityprompts.RTPThreat,snowball,xss
  extended_detectors: false


